### ISSUE TITLE
The specified URL did not find the Supplementary Table

### ISSUE THREAD

**Issue by yanyan1028** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#10]
Thank you for providing the paper and dataset.
When I looked for the Supplementary Table according to the additional information at the end of the paper, I didn’t find it, i really want to fully understand this brilliant paper from Nature.
Thank you.

**Comment by petermattia** [comment]
The SI is available here:
https://static-content.springer.com/esm/art%3A10.1038%2Fs41560-019-0356-8/MediaObjects/41560_2019_356_MOESM1_ESM.pdf
