### ISSUE TITLE
question about the data column 'Qc'

### ISSUE THREAD

**Issue by Txiaoxiao** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#11]
hey, I'm using your data for study, and i'm in doubt about the column 'Qc' in cycles. why the length of 'Qc' of each cycle is equal to other columns like 't' and 'Qd'. didn't you measure Qc when charging and Qd when discharging? I am looking forward to your reply, thanks.

**Comment by petermattia** [comment]
Hi Txiaixiao, Qc doesn’t change during discharging, and Qd doesn’t change during charging. Plotting both quantities vs time should make this clear (initially Qc will increase and Qd will be 0, and then Qd will increase and Qc will be constant). This structure mirrors how the Arbin cycler treats these capacities as separate. Hope this helps.

Peter

On Sep 9, 2019, at 10:52 PM, Txiaoxiao <notifications@github.com<mailto:notifications@github.com>> wrote:


hey, I'm using your data for study, and i'm in doubt about the column 'Qc' in cycles. why the length of 'Qc' of each cycle is equal to other columns like 't' and 'Qd'. didn't you measure Qc when charging and Qd when discharging? I am looking forward to your reply, thanks.

**Comment by Txiaoxiao** [comment]
Thanks for your detailed answer, now I can understand it very clearly,  it's a big help for me, thanks very much!

**Comment by zhangwenhk** [comment]
Hello, petermattia, it's hard to recurrent the features used in this paper, for some notations like $q$ or $\Delta Q(V)$ were defined ambiguously in **Supplementary Note 1. Feature formulations**, I am wondering whether the source programm about feature extraction can be provided?

**Comment by zhangwenhk** [comment]
@petermattia Thanks, that has been done!
