### ISSUE TITLE
Model Code required.

### ISSUE THREAD

**Issue by ravishk1** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#13]
Hi @petermattia , I am curious to know more about the model architecture as my model was not able to replicate the accuracy measures. It's written in the paper that model architecture will be available on request. So will you please share it. My email id is :- ravishrajiitk@gmail.com

**Comment by petermattia** [comment]
Please contact Richard Braatz at braatz@mit.edu for the academic license
