### ISSUE TITLE
Internal Resistance Measurement Specification

### ISSUE THREAD

**Issue by totteCh** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#15]
From the paper:

> An internal resistance measurement was obtained during charging at 80% SOC by averaging 10 pulses of ±3.6 C with a pulse width of 30 or 33 ms, where 1 C is 1.1 A, or the current required to fully (dis)charge the nominal capacity (1.1 Ah) in 1 h.

How long were the pauses between the pulses, and why did the pulse widths vary?

**Comment by petermattia** [comment]
The pause between the pulses is the pulse width. We experimented with two slight differences, but the values are pretty comparable across the whole dataset.
