### ISSUE TITLE
Does anyone have the code for feature extraction？

### ISSUE THREAD

**Issue by YouzhiHe** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#18]
I am a student. I want to use the dataset from this Nature Energy article. The data set is relatively large, and the author only provides part of the preprocessing code, which cannot be directly used for machine learning prediction. So I want to know if anyone can share your preprocessing and feature extraction code? If you can provide it, it would be greatly appreciated!

**Comment by petermattia** [comment]
Hi @YouzhiHe, unfortunately the full code requires an academic license to access :(

I wrote a new paper with Kristen on this work, which has fully open code and data. Perhaps this could be a starting point for you and others. 
https://github.com/petermattia/revisit-severson-et-al 

Closing for now.

**Comment by YouzhiHe** [comment]
Thank you very much for answering my questions in your busy schedule. 
I have noticed your new paper and my problem has been solved. 
Thank you!
