### ISSUE TITLE
Is the BEEP structured data clean?

### ISSUE THREAD

**Issue by smedegaard** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#21]
Thanks a lot for the work on this dataset, and for releasing it.

it's unclear to me if the the [BEEP structured data](https://data.matr.io/1/projects/5c48dd2bc625d700019f3204) (.json) files is raw data or has it been cleaned?

**Comment by petermattia** [comment]
Defer to @patrickherring-TRI as he prepared this data

**Comment by patrickherring-TRI** [comment]
@smedegaard The structured data (*.json) has been cleaned and processed. Cycling data has been interpolated to a uniform axis and summary information has been computed

**Comment by smedegaard** [comment]
Thank you @patrickherring-TRI

**Comment by smedegaard** [comment]
@patrickherring-TRI , just to be sure.
The reading the "summary" attribute of each *.json file in the BEEP dataset is equivalent to running the code in BuildPkl_Batch[1-3].ipynb?
I want to train a neural network with the data, but besides your comment above, I miss information on what is done with the data in BEEP.
And again, thank you very much for the work and for sharing the data.

**Comment by frknayk** [comment]
For the structured data voltage curves looks wrong (cycles_interpolated) since when discharging event happens voltage goes constantly and linearly goes up.

**Comment by Roy027** [comment]
I am also very sure about the usage of the BEEP dataset. Can we have some starter code for this BEEP dataset as well?

**Comment by Saltsmart** [comment]
> For the structured data voltage curves looks wrong (cycles_interpolated) since when discharging event happens voltage goes constantly and linearly goes up.

![image](https://user-images.githubusercontent.com/40828952/203006119-dbf9d9d0-fe3b-4c6f-a9d8-25a7abdb6420.png)

@frknayk I also notice this. It's weird!
