### ISSUE TITLE
Standardization of discharge curve

### ISSUE THREAD

**Issue by Heyuong** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#24]
Hello, in the cycle process, how to handle the capacity-voltage curve standardization of all discharge curves of 4C, and what are the steps of smooth spline function fitting? Thank you very much

**Comment by petermattia** [comment]
Hi, you'll need to obtain the academic license to view the code for this step. In short, the discharge curves were fit to a spline, which was subsequently evaluated at 1000 voltage points to obtain Qdlin.

**Comment by petermattia** [comment]
Actually, I take back what I said -- you can view the code for this here:
https://github.com/chueh-ermon/BMS-autoanalysis/blob/master/VQlinspace.m
