### ISSUE TITLE
Time interval between two discharge time step

### ISSUE THREAD

**Issue by Katezhouqi** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#33]
Could you please provide information about the frequency of measurements taken at the discharge sample point? Specifically, I am interested in knowing the time interval between two consecutive discharge measurements. Thank you!

**Comment by JoachimSchaeffer** [comment]
The measurement frequency is not constant. You can find the specific time in the data. Hope the attached figures helps.

![Sampling_LFP_Data](https://github.com/rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation/assets/63883039/00529fb5-8a99-4c76-b65a-a85e190c8545)

**Comment by Katezhouqi** [comment]
thank you, may i know where did you get the time information?

**Comment by JoachimSchaeffer** [comment]
You should be able to reproduce the plot with the data which is open-access. You might want to have a look at the data processing steps.

**Comment by Katezhouqi** [comment]
Thank you!
