### ISSUE TITLE
Batch 2017-05-12 and 2017-06-30

### ISSUE THREAD

**Issue by Katezhouqi** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#34]
When the battery SOH is 100% or nearly 100%, the discharge time steps in a discharge cycle is around 330 and above. While in Batch 2018-04-12 and Batch9, the discharge time step is slightly above 260. May I know what cause the huge gap? The only difference from the paper is the charging current. (correct me if I am reading wrongly.) Is there any reason that the batteries from these batches (Batch 2017-05-12 and 2017-06-30) are significantly performing better than the other two batches.

**Comment by JoachimSchaeffer** [comment]
1. Please keep the time step discussion to a single thread. 
2. Please have a look at the supplementary information of: https://www.nature.com/articles/s41586-020-1994-5
The cells in the third batch were stored longer (more calendar aging) which has an influence on the aging trajectory "path dependency". Please compare the charging protocol C-rates of the protocols associated with the longer lasting cells with the charging protocol C-rates associated with the shorter lived cells.

**Comment by Katezhouqi** [comment]
Thank you for your input. I believe that calendar aging has a more significant impact on the reduced lifespan of cells compared to the charging protocol C-rates. However, I'm not entirely certain about the accuracy of this statement.

**Comment by JoachimSchaeffer** [comment]
It is very difficult to understand what exactly you mean.  Please provide a source and reasoning why do you believe your claim is justified. 

If your question got resolved, please close this issue.

**Comment by Katezhouqi** [comment]
Thank you, I will close the issue.
