### ISSUE TITLE
what is Frequency rate of data collection and unit of time.

### ISSUE THREAD

**Issue by RonakGajera999** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#35]
Hi, I am struggling with time series analysis while the dataset frequency rate(sampling rate) of the data acquisition method is not described in the research paper. can you please elaborate more about the what is the time stamp unit and at which rate you collect data from the battery.

**Comment by JoachimSchaeffer** [comment]
Please have a look at issue #33 
Let me know whether that resolves your question.

**Comment by RonakGajera999** [comment]
thank you for the issue but how do you tell it in a minute time frame? while completing one cycle of charging time (0 to 80%) to average 9 to 13.3 minutes, from 80 to 100% with 1C CC-CV with current cutoff C/50 it really takes time 2.5 minutes? and discharge 4C rate 15 minutes.

**Comment by RonakGajera999** [comment]
thank you for the information but how do we tell it in a minute time frame? while completing one cycle of charging time (0 to 80%) to average 9 to 13.3 minutes, from 80 to 100% with 1C CC-CV with current cutoff C/50 it really takes time 2.5 minutes? and discharge 4C rate 15 minutes. while what is the representation of the difference between two consecutive time points is too narrow and some points it even similar. so I am confused that what the should be concrete unit for time here.

**Comment by petermattia** [comment]
Thanks for the reply @JoachimSchaeffer!

Often in battery cycling, we log data every X seconds (eg 5 seconds) and Y change in voltage (eg 1 mV). This practice ensures that we log frequently (time component) while not missing any dramatic changes in voltage (voltage component). Thus, the time spacing is not uniform in the dataset.

**Comment by JoachimSchaeffer** [comment]
Thanks, @petermattia that's a perfect explanation for the figure in #33 .
