### ISSUE TITLE
Do not find Python data files

### ISSUE THREAD

**Issue by wsyxbcl** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#4]
First, thank you for providing the dataset.

But I fail to find the data file for Python (.pkl) at https://data.matr.io/1/. I would like to know whether it has been available.

Thank you.

**Comment by fa1247** [comment]
I think you need to build .pkl file from .mat file with BuildPkl_BatchX.ipynb by yourself.

**Comment by wsyxbcl** [comment]
> I think you need to build .pkl file from .mat file with BuildPkl_BatchX.ipynb by yourself.

OK, I get it.

Thanks for the reply.

**Comment by petermattia** [comment]
Yes, we did not want to provide downloadable pickle files due to security issues with this file format.
