### ISSUE TITLE
Matlab file(.mat) has something error

### ISSUE THREAD

**Issue by LYC878484** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#6]
Thank you for providing the dataset.
When I run the program(LoadData. m) on matlab,  an error occurred which is unable to read MAT-file.  and to test is there something wrong in                                                                                  2018-04-12_batchdata_updated_struct_errorcorrect.mat,  I use the command load('2018-04-12_batchdata_updated_struct_errorcorrect.mat'),  The result is the same. 
I would like to know is there something wrong with my operation? 
Thank you.

**Comment by petermattia** [comment]
Apologies for the delayed response. Do you still have this problem?

**Comment by LYC878484** [comment]
Thank you for reply, my ability limit me and I am not able to solve this problem.
I think the problem may be from the data that is available at https://data.matr.io/1/. So I want get your help. Could you try to run this progrom again and  send it to me(i am from chinese and email:1247899437@qq.com).It may be somewhat abrupt, but i really want to fully understand this brilliant paper from Nature,Thank you!

**Comment by LYC878484** [comment]
> Apologies for the delayed response. Do you still have this problem?

Thank you for reply, my ability limit me and I am not able to solve this problem.
I think the problem may be from the data that is available at https://data.matr.io/1/. So I want get your help. Could you try to run this progrom again and send it to me(i am from chinese and email:1247899437@qq.com).It may be somewhat abrupt, but i really want to fully understand this brilliant paper from Nature,Thank you!

**Comment by LYC878484** [comment]
> Apologies for the delayed response. Do yo

**Comment by petermattia** [comment]
Is it only the 2018-04-12_batchdata_updated_struct_errorcorrect.mat file, or are other files affected?
