### ISSUE TITLE
Question about "Integral of temperature over time, cycles 2 to 100"

### ISSUE THREAD

**Issue by moxkari** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#8]
Hello,

We're trying to figure out how to reproduce this feature described in your paper:
Temperature integral, cycle 2 to 100 = ∫𝑡_100 t_2 𝑇(𝑡)𝑑𝑡

Wondering if it has some correlation to the "Tdlin" values in the dataset.  Any pointers would be appreciated!

**Comment by petermattia** [comment]
This feature is presented on lines 87-119 of FullModel.m. To access the code, please contact Richard Braatz (braatz@mit.edu) for the academic license.
